Update UnitTests.yml

diff --git a/.github/workflows/UnitTests.yml b/.github/workflows/UnitTests.yml
--- a/.github/workflows/UnitTests.yml
+++ b/.github/workflows/UnitTests.yml
@@ -35,10 +35,11 @@ jobs:
 
       - name: Test
         run: dotnet test --no-restore --configuration Release --filter "UnitTests" --logger "console;verbosity=detailed"
-        continue-on-error: true
 
       - name: Check test results
-        if: failure()
+        if: failure() || success()
         run: |
-          echo "Tests failed on ${{ matrix.os }}"
-          exit 1
+          if [ $? -ne 0 ]; then
+            echo "Tests failed on ${{ matrix.os }}"
+            exit 1
+          fi
