Update UnitTests.yml

diff --git a/.github/workflows/UnitTests.yml b/.github/workflows/UnitTests.yml
--- a/.github/workflows/UnitTests.yml
+++ b/.github/workflows/UnitTests.yml
@@ -35,15 +35,29 @@ jobs:
 
       - name: Test
         run: dotnet test --no-restore --configuration Release --filter "UnitTests" --logger "console;verbosity=detailed"
-        continue-on-error: true # Continue even if tests fail to allow other OSs to complete
+        continue-on-error: true # Continue even if tests fail to ensure all OSs complete their runs
 
-      - name: Check test results
-        if: always() # Ensure this step runs regardless of the test result
+      - name: Save test result for ${{ matrix.os }}
+        id: test_result
         run: |
           if [ $? -ne 0 ]; then
-            echo "Tests failed on ${{ matrix.os }}"
+            echo "Test failed on ${{ matrix.os }}"
+            echo "::set-output name=test_result::fail"
+          else
+            echo "Test passed on ${{ matrix.os }}"
+            echo "::set-output name=test_result::pass"
           fi
-          
-      - name: Fail the job if any OS fails
-        if: failure()
-        run: exit 1
+
+  # This job runs after all OS-specific jobs and determines the overall result
+  summarize:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Fail if any test failed
+        run: |
+          # Check the outcome of each matrix OS
+          if [[ "${{ needs.build.outputs.test_result }}" == "fail" ]]; then
+            echo "Some tests failed."
+            exit 1
+          else
+            echo "All tests passed."
